version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5732:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keyline

  mail:
    image: axllent/mailpit:v1.26
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

  vault:
    image: vault:1.13.3
    ports:
      - "8222:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot

  redis:
    image: valkey/valkey
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  keyline-ui:
    image: ghcr.io/the127/keyline-ui:v0.1.4
    platform: linux/amd64
    container_name: keyline-ui
    ports: ["5173:80"]
    environment:
      KEYLINE_API_URL: "http://localhost:8081"
      KEYLINE_HOST: "http://localhost:5173"
    restart: unless-stopped